const Data = [
  {
    id: 1,
    title: "Brown eggs",
    type: "dairy",
    description: "Raw organic brown eggs in a basket",
    filename: "0.jpg",
    height: 600,
    width: 400,
    price: 28.1,
    rating: 4,
  },
  {
    id: 2,
    title: "Legums",
    type: "vegetable",
    description: "Cooked legums on the wooden table",
    filename: "11.jpg",
    height: 600,
    width: 399,
    price: 14.77,
    rating: 0,
  },
  {
    id: 3,
    title: "Fresh tomato",
    type: "vegetable",
    description: "Fresh tomato juice with basil",
    filename: "12.jpg",
    height: 600,
    width: 903,
    price: 16.3,
    rating: 2,
  },
  {
    id: 4,
    title: "Healthy breakfast",
    type: "fruit",
    description:
      "Healthy breakfast set. rice cereal or porridge with berries and honey over rustic wood background",
    filename: "13.jpg",
    height: 450,
    width: 350,
    price: 13.02,
    rating: 2,
  },
  {
    id: 5,
    title: "Green beans",
    type: "vegetable",
    description: "Raw organic green beans ready to eat",
    filename: "14.jpg",
    height: 450,
    width: 300,
    price: 28.79,
    rating: 1,
  },
  {
    id: 6,
    title: "Baked stuffed portabello mushrooms",
    type: "bakery",
    description:
      "Homemade baked stuffed portabello mushrooms with spinach and cheese",
    filename: "15.jpg",
    height: 600,
    width: 400,
    price: 20.31,
    rating: 1,
  },
  {
    id: 7,
    title: "Strawberry jelly",
    type: "fruit",
    description: "Homemade organic strawberry jelly in a jar",
    filename: "16.jpg",
    height: 400,
    width: 600,
    price: 14.18,
    rating: 1,
  },
];

export default Data;
